const AUTH_USER = '''
 user {
              id
              name
              is_social
              is_verified
              id_color
              info
              open_time
              close_time
              total_views
              is_available_create
              communities{
                id
                name
                users{
                name
                seller_name
                id
                }
              }
              unread_notifications_count
              seller_name
              email_verified_at
              email
              level
              address
              phone
              phone_code
              full_phone
              is_seller
              image
              logo
              total_balance
              total_point
              following_count
              invoices_count
              invoices_seller_count
         special_product_count
advices_count
              info
              following_count
              total_balance
              total_point
              is_seller
              can_create_channel
              can_create_group
              affiliate
              is_active
              social{
                twitter
                face
                instagram
                linkedin
                tiktok
              }
           
              plans{
                id
                name
                ads_count
                special_count
                duration
                type
                pivot{
                 expired_date
                 subscription_date
                }
              }
            
              city {
                name
                id
                 city_id
              }
              area {
                name
                id
                code_city
                level
              }
              followers {
                 seller{
                    id
                }
            }
        }
''';

const AUTH_FIELDS = '''
              id
              name
                is_social
              is_verified
              invoices_count
              invoices_seller_count
              id_color
              info
              open_time
              close_time
              total_views
              special_product_count
              advices_count
              is_available_create
              is_active
              communities{
                id
                name
                users{
                  name
                  seller_name
                  id
                }
              }
              unread_notifications_count
              seller_name
              email_verified_at
              email
              level
              address
              phone
              phone_code
              full_phone
              is_seller
              image
              logo
              total_balance
              total_point
              following_count
              affiliate
         
              info
              following_count
              total_balance
              total_point
              is_seller
              can_create_channel
              can_create_group
           
              social{
                twitter
                face
                instagram
                linkedin
                tiktok
              }
           
              plans{
                id
                name
                 duration
                type
                ads_count
                special_count
                products_count
                pivot{
                  expired_date
                  subscription_date
                }
            }
            
               city {
                  name
                  id
                  code_city
                  level
                  children{
                    id 
                    code_city 
                    level
                    name
                  }
              }
             area {
                name
                id
                code_city
                level
            }
            followers {
                seller{
                id
                }
            }
''';
