// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9BKncJV4nAbBN_eRfkE5cjyK2uL9Dxo',
    appId: '1:48907040413:android:d6e6a37a13e31fea078674',
    messagingSenderId: '48907040413',
    projectId: 'peaceful-nature-376111',
    storageBucket: 'peaceful-nature-376111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdYxAIU__5Tf-FC6emj5dw6eeh2EK2eiw',
    appId: '1:48907040413:ios:faffe4ae16f9433e078674',
    messagingSenderId: '48907040413',
    projectId: 'peaceful-nature-376111',
    storageBucket: 'peaceful-nature-376111.firebasestorage.app',
    androidClientId: '48907040413-9rb80gs53052qt1eajpalqqp54tedmtq.apps.googleusercontent.com',
    iosClientId: '48907040413-7huutuodhfc4h9j85apnto9ka8qle6e3.apps.googleusercontent.com',
    iosBundleId: 'com.mada.company.ali.basha',
  );
}
